---
# tasks file for lens | EL Family

- name: EL Family | Downloading and installing {{ lens_app }} {{ lens_version }}
  ansible.builtin.yum:
    name: "{{ lens_el_url }}"
    state: "{{ lens_desired_state }}"
    disable_gpg_check: yes
